config/routes.rb
Rails.application.routes.draw do
  resources :searches
  devise_for :users
  root "events#index"
  resources :events
  resources :users
  get "some_another_url", to: "events#index"
  resources :comments
  get "home/index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, counter_cache: true
  belongs_to :event

  validates :body, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, :body, :place, :date_from, :date_to, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :event
  belongs_to :search
  scope :unread, -> { where(read_at: nil) }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, as: :commentable
  has_many :commentators, through: :comments, source: :user
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user

  def params_of_filtr
    attributes.except("id", "user_id", "created_at", "updated_at").map { |key, object| { "#{key}": object.to_s } }.reduce(:merge)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  before_destroy :log_before_destroy
  after_destroy :log_after_destroy

  validates :name, presence: true
  validates :name, length: { maximum: 16, minimum: 2 }
  validates :name, uniqueness: true

  has_many :events, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :commented_posts, through: :comments, source: :Event
  has_many :searches, dependent: :destroy

  has_many :commented_users, through: :comments, source: :commentable, source_type: :User

  private

  def log_before_destroy
    Rails.logger.info "record with name = #{name} will be deleted soon"
  end

  def log_after_destroy
    Rails.logger.info "record with name = #{name} already deleted"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  prepend_view_path Rails.root.join "app", "javascript"

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.event, notice: "Commment was successfully created." }

      else
        format.html { redirect_to @comment.event, notice: "Commment can't be empty." }
      end
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.permit(:user_id, :body, :event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: %i[show edit update destroy]
  # GET /events
  # GET /events.json
  def index
    @events = Event.includes(:user).page(params[:page]).per(3)
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @comments = @event.comments.order(:created_at).page(params[:page]).per(10)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        NotifierService.call(@event)

        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event)
          .permit(:title, :body, :user_id, :place, :date_from, :date_to, :visible)
          .merge(body: [params[:event][:body]])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  # GET /searches
  # GET /searches.json
  def index
    @searches = SearchService.call(search_params)
    @inserted_data = search_params
  end

  # # GET /searches/1
  # # GET /searches/1.json
  def show
    search_params_of_filtr = Search.find(search_params[:id]).params_of_filtr
    @searches = SearchService.call(search_params_of_filtr)
  end

  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: "Search was successfully created." }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def search_params
    params.permit(:id, :user_id, :search_place, :search_start_beg, :search_start_end, :search_subject)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.page(params[:page]).per(5)
    @notifications = Notification.where(user_id: current_user).unread
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @filtres = User.find(current_user.id).searches
    @notifications = Notification.where(user_id: current_user).unread
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :comments_count)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/events/_commentform.html.slim
= form_tag "/comments" do
 = hidden_field_tag :user_id, current_user.id
 = hidden_field_tag :event_id, @event.id


 .form-group

   .col-sm-2.control-label
    = label_tag t('event.add_comment')

   .col-sm-10
    = text_field_tag :body, value = nil, class: "form-control"

 .form-group
  .col-sm-offset-2.col-sm-10
    = submit_tag "#{t('event.add')}", class: "btn btn-success"

app/views/events/_event.html.slim
.event_title
  = event.title
.event_info_nav
  .n #{t('event.author')}: #{event.user.name}
  .n #{t('event.place')}: #{event.place}
  .n #{t('event.start')}: #{event.date_from}
  .n #{t('event.end')}: #{event.date_to}
.event_body
  h4  #{t('event.topics_of_event')}:
  -event.body.each do |event|
    p
    = event
.event_body_nav
  = link_to t('event.Show'), event if title == "all"
  = link_to t('event.Edit'), edit_event_path(event) if event.user == current_user
  = link_to t('event.Destroy'), event, data: { confirm: t('event.sure')}, method: :delete if event.user == current_user
  = link_to t('event.Back'), events_path if title == "one"

app/views/events/_form.html.slim
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      h2 = "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      ul
        - @event.errors.full_messages.each do |message|
          li = message
  = f.hidden_field :user_id, value: current_user.id
  .form-group
    .col-sm-2.control-label
      = f.label :title

    .col-sm-10
      = f.text_field :title, class: "form-control"

  .form-group
    .col-sm-2.control-label
      = f.label :body

    .col-sm-10
      = f.text_area :body, class: "form-control"

  .form-group
   .col-sm-2.control-label
     = f.label "Place:"

   .col-sm-10
     = f.text_field :place, class: "form-control"

  .form-group
   .col-sm-2.control-label
     = f.label "Start day:"
   .col-sm-10
     = f.date_field :date_from, class: "form-control"

   .col-sm-2.control-label
     = f.label "End day:"
   .col-sm-10
     = f.date_field :date_to, class: "form-control"

  .form-group
    .col-sm-offset-2.col-sm-10
      .actions
       = f.submit nil, class: "btn btn-success"

app/views/events/edit.html.slim
h1 #{t("event.Editing_event")}

== render 'form'

=> link_to t('event.Show'), @event
'|
=< link_to t('event.Back'), events_path

app/views/events/index.html.slim
h1 #{t("event.Listing_events")}

table class="event_head"

  tbody
    = render  @events, title: "all"

br

p
  = link_to 'New Event', new_event_path

p class="pagination"
 = paginate  @events

app/views/events/new.html.slim
h1 #{t("event.New_event")}

== render 'form'

= link_to t('event.Back'), events_path

app/views/events/show.html.slim
p#notice = notice

== render @event, title: "one"


.event_body
  strong  #{t("event.Comments")}:

  - @comments.each  do  |comment|
   .comment
    .
     b = comment.user.name + ":"
    .
     = comment.body

p class="pagination"
  = paginate  @comments


== render "commentform"

app/views/home/index.html.slim
/ p wow, you visit #{session[:times_here]} times

h1.page-header  Домашняя страница
p.alert.alert-primary Find me  in app/views/home/index.html.slim
= render  "components/page/page"  do
  p.alert.alert-success  Hello from  our first component!

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Event's blog
    = csrf_meta_tags
    = javascript_pack_tag  'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload'
  body
    = render 'shared/header'
    = yield

app/views/posts/_form.html.slim
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :visible
    = f.check_box :visible
  .actions = f.submit

app/views/posts/show.html.slim
p#notice = notice

p
  strong Title:
  = @post.title
p
  strong Body:
  = @post.body
p
  strong User:
  = @post.user.name
/ p
/  strong Visible:
/  = @post.visible
p
  strong  Comments:
  table
   -@comments.each  do  |comment|
    tr
      td: b  = comment.user.name
      td  = comment.body

p class="pagination"
  = paginate  @comments

=> link_to 'Edit', edit_post_path(@post)
'|
=< link_to 'Back', posts_path

app/views/searches/_form.html.slim
= form_tag(searches_path, method: :get, class: "search_form") do
 .form-group
  .col-sm-2.control-label
    = label_tag(:search_place, t('search.city'))

  .col-sm-10
    = text_field_tag(:search_place, params[:search], class: "form-control")
 .form-group
  .col-sm-2.control-label
    = label_tag(:search_start_beg, t('search.start'))
  .col-sm-10
    = date_field_tag(:search_start_beg, params[:search_start_beg], class: "form-control")
  .col-sm-2.control-label
    = label_tag(:search_start_end, t('search.end'))
  .col-sm-10
    = date_field_tag(:search_start_end, params[:search_start_end], class: "form-control")
 .form-group
  .col-sm-2.control-label
    = label_tag(:search_start, t('search.subject'))
  .col-sm-10
    = text_field_tag(:search_subject, params[:search_subject],class: "form-control")
 p
 .form-group
  .col-sm-offset-2.col-sm-10
    = submit_tag(t('search.search'), class: "btn btn-success")

app/views/searches/_result.html.slim
- print_out = [t("search.city"), t("search.range"), t("search.subject")]


/ - if @searches.present?
/   - @searches.each_with_index do |object, index|
/     p
/     - if object.nil?
/       = print_out[index] + " #{t('search.not_entered')}"
/     - elsif object.kind_of?(Array) & object.compact.empty?
/       = print_out[index] +  " #{t('search.not_found_array')}"

br
- if !@searches.kind_of?(Class)
  h2 #{t("search.result")}
  p

  - @searches.map do |event|
    p
      = event.title
      ="  "
      = link_to t('search.show'), event
  / - if !@searches.compact.map {|object| object.compact.empty?}.all? {|object| object.eql?(false)}
  /   = t("search.not_found")
  / - if @searches.compact.flatten.compact.size == 1
  /   - @searches.compact.flatten.compact.map do |event|
  /     p
  /       = event.title
  /       ="  "
  /       = link_to t('search.show'), event
  / - else
  /   - @searches.map do |event|
  /     p
  /       = event.title
  /       ="  "
  /       = link_to t('search.show'), event
  - if @inserted_data.present?
    p
      = form_tag "searches" do
        = hidden_field_tag :user_id, current_user.id
        - @inserted_data.each do |key,value|
          = hidden_field_tag key,value
        = submit_tag t('search.save_result'), class: "btn btn-success"

app/views/searches/edit.html.slim
h1 Editing search

== render 'form'

=> link_to t('search.show'), @search
'|
=< link_to t('search.back'), searches_path

app/views/searches/index.html.slim
h1 #{t('search.listing_searches')}


== render 'form'

== render 'result'

app/views/searches/new.html.slim
h1 #{t('search.new_search')}

== render 'form'

= link_to 'Back', searches_path

app/views/searches/show.html.slim
p#notice = notice


== render 'result'

/=> link_to 'Edit', edit_search_path(@search)
/'|
/=< link_to 'Back', searches_path

app/views/shared/_header.html.slim
header

  ul.nav.nav-pills
    - if user_signed_in?
      li
        span  = t('label.hello') % current_user.name
      li.activ
        = link_to t('label.log_out'), destroy_user_session_path, method:  :delete
    -else
      li.activ
        = link_to  t('label.login'), new_user_session_path
      li.activ
        = link_to  t('label.registration'), new_user_registration_path


  ul.nav.nav-pills

    - if user_signed_in?

      li
      .dropdown
        button  aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" type="button"
          | Notifications
          =" "

          span id="dropdown"
        .dropdown-menu id='dropdown-menu' aria-labelledby="dropdownMenuButton"

      li
        = link_to t('label.about_user'), user_path(current_user.id)
      li
        = link_to t('label.events'), events_path
      li
        = link_to t('label.search'), searches_path



/        li
/          = link_to 'Мои комменты', users_path
/        - if user_signed_in? && current_user.moderator?
/          li
/            = link_to 'Встречи', events_path
/          li
/            = link_to 'Пользователи', users_path
/
/ a#dropdownMenu1.dropdown-toggle.nav-link aria-expanded="false" aria-haspopup="true" data-behavior="notifications-link" data-toggle="dropdown" type="button"

/ = link_to 'catering', events_path,   data: {behavior: "notifications"}
/  , id: { behavior: "notifications"}

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email

  .actions = f.submit

app/views/users/edit.html.slim
h1 #{t('user.editing_user')}

== render 'form'

=> link_to t('user.show'), @user
'|
=< link_to t('user.back'), users_path

app/views/users/index.html.slim
h1 #{t('user.listing_users')}
table class="user_body"
  thead
    tr
      th #{t('user.Name')}
      th #{t('user.Email')}
      th #{t('user.Comments')}
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.name
        td = user.email
        td = user.comments_count
        td = link_to t('user.show'), user
        td = link_to t('user.edit'), edit_user_path(user)
        td = link_to t('user.destroy'), user, data: { confirm: t('user.sure') }, method: :delete

br



= link_to t('user.new_user'), new_user_path

p class="pagination"
 = paginate  @users

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

p
  strong Name:
  = " "
  = @user.name
p
  strong Email:
  =  " "
  = @user.email
p
  strong Comments count:
  = " "
  = @user.comments_count
- if @filtres.size > 0
  h2 Filtres

- number_of_filtr = 0
-@filtres.each do |filtr|
  .filtr
    - number_of_filtr += 1
    = link_to "Filtr №" + number_of_filtr.to_s, search_path(filtr.id)
    p

       - @notifications.each do |notification|
        p
          = notification.event.title if notification.search_id == filtr.id
          = '   '
          = link_to "Go to event", Event.find(notification.event_id)  if notification.search_id == filtr.id


=> link_to t('search.edit'), edit_user_path(@user)
'|
=< link_to t('search.back'), users_path